import '@servicenow/sdk/global'
import { Record } from '@servicenow/sdk/core'

// Enhanced insurance customer records with new fields: risk, clv, renewal_date, engagement_score

export const enhanced_policy_holder_1 = Record({
  $id: Now.ID['enhanced_policy_holder_3001'],
  table: 'x_hete_clv_maximiz_policy_holders',
  data: {
    customer_id: 'CUST-2024-3001',
    first_name: 'Jennifer',
    last_name: 'Martinez',
    name: 'Jennifer Martinez',
    email: 'jennifer.martinez@familytech.com',
    phone: '+15553001',
    age: 34,
    credit_score: 742,
    churn_risk: 15,
    risk: 'low',
    tier: 'gold',
    lifetime_value: 48500,
    clv: 12500,
    renewal_date: '2025-03-15',
    engagement_score: 85,
    tenure_years: 6,
    preferred_channel: 'Mobile App',
    app_sessions_30_days: 28,
    website_visits_30_days: 15,
    quote_views: 3,
    clv_score: 7.8,
    credit_utilization_percent: 22,
    number_of_open_accounts: 4,
    number_of_closed_accounts: 2,
    delinquency_12m: 0,
    credit_inquiries_last_6m: 1,
    bankruptcies_flag: false,
    abandoned_journeys: 1,
    avg_session_time_min: 8,
    risk_flags: 'Tech Professional, Stable Income',
    missing_coverage: 'Identity Theft Protection'
  }
});

export const enhanced_policy_holder_2 = Record({
  $id: Now.ID['enhanced_policy_holder_3002'],
  table: 'x_hete_clv_maximiz_policy_holders',
  data: {
    customer_id: 'CUST-2024-3002',
    first_name: 'Robert',
    last_name: 'Chen',
    name: 'Robert Chen',
    email: 'robert.chen@medpractice.health',
    phone: '+15553002',
    age: 45,
    credit_score: 798,
    churn_risk: 8,
    risk: 'low',
    tier: 'platinum',
    lifetime_value: 95000,
    clv: 28500,
    renewal_date: '2025-02-28',
    engagement_score: 92,
    tenure_years: 12,
    preferred_channel: 'Phone',
    app_sessions_30_days: 15,
    website_visits_30_days: 8,
    quote_views: 2,
    clv_score: 9.1,
    credit_utilization_percent: 8,
    number_of_open_accounts: 6,
    number_of_closed_accounts: 1,
    delinquency_12m: 0,
    credit_inquiries_last_6m: 0,
    bankruptcies_flag: false,
    abandoned_journeys: 0,
    avg_session_time_min: 12,
    risk_flags: 'Healthcare Professional, High Income',
    missing_coverage: 'Malpractice Liability Increase'
  }
});

export const enhanced_policy_holder_3 = Record({
  $id: Now.ID['enhanced_policy_holder_3003'],
  table: 'x_hete_clv_maximiz_policy_holders',
  data: {
    customer_id: 'CUST-2024-3003',
    first_name: 'Sarah',
    last_name: 'Williams',
    name: 'Sarah Williams',
    email: 'sarah.williams@startup.biz',
    phone: '+15553003',
    age: 29,
    credit_score: 678,
    churn_risk: 42,
    risk: 'medium',
    tier: 'silver',
    lifetime_value: 32000,
    clv: 8500,
    renewal_date: '2025-04-20',
    engagement_score: 68,
    tenure_years: 3,
    preferred_channel: 'Mobile App',
    app_sessions_30_days: 45,
    website_visits_30_days: 32,
    quote_views: 8,
    clv_score: 5.9,
    credit_utilization_percent: 48,
    number_of_open_accounts: 3,
    number_of_closed_accounts: 1,
    delinquency_12m: 1,
    credit_inquiries_last_6m: 3,
    bankruptcies_flag: false,
    abandoned_journeys: 6,
    avg_session_time_min: 4,
    risk_flags: 'Entrepreneur, Variable Income',
    missing_coverage: 'Business Interruption, Life Insurance'
  }
});

export const enhanced_policy_holder_4 = Record({
  $id: Now.ID['enhanced_policy_holder_3004'],
  table: 'x_hete_clv_maximiz_policy_holders',
  data: {
    customer_id: 'CUST-2024-3004',
    first_name: 'Michael',
    last_name: 'Johnson',
    name: 'Michael Johnson',
    email: 'michael.johnson@construction.pro',
    phone: '+15553004',
    age: 52,
    credit_score: 615,
    churn_risk: 75,
    risk: 'high',
    tier: 'bronze',
    lifetime_value: 18500,
    clv: 4500,
    renewal_date: '2025-01-30',
    engagement_score: 35,
    tenure_years: 8,
    preferred_channel: 'Phone',
    app_sessions_30_days: 5,
    website_visits_30_days: 3,
    quote_views: 15,
    clv_score: 3.2,
    credit_utilization_percent: 78,
    number_of_open_accounts: 2,
    number_of_closed_accounts: 4,
    delinquency_12m: 3,
    credit_inquiries_last_6m: 8,
    bankruptcies_flag: false,
    abandoned_journeys: 12,
    avg_session_time_min: 2,
    risk_flags: 'Construction Industry, Economic Sensitivity, High Utilization',
    missing_coverage: 'Workers Compensation, Equipment Coverage'
  }
});

export const enhanced_policy_holder_5 = Record({
  $id: Now.ID['enhanced_policy_holder_3005'],
  table: 'x_hete_clv_maximiz_policy_holders',
  data: {
    customer_id: 'CUST-2024-3005',
    first_name: 'Emily',
    last_name: 'Davis',
    name: 'Emily Davis',
    email: 'emily.davis@education.school',
    phone: '+15553005',
    age: 38,
    credit_score: 720,
    churn_risk: 25,
    risk: 'low',
    tier: 'silver',
    lifetime_value: 35000,
    clv: 9500,
    renewal_date: '2025-06-15',
    engagement_score: 78,
    tenure_years: 7,
    preferred_channel: 'Email',
    app_sessions_30_days: 18,
    website_visits_30_days: 12,
    quote_views: 4,
    clv_score: 6.8,
    credit_utilization_percent: 28,
    number_of_open_accounts: 3,
    number_of_closed_accounts: 1,
    delinquency_12m: 0,
    credit_inquiries_last_6m: 2,
    bankruptcies_flag: false,
    abandoned_journeys: 2,
    avg_session_time_min: 7,
    risk_flags: 'Education Sector, Stable Employment',
    missing_coverage: 'Disability Insurance Enhancement'
  }
});

export const enhanced_policy_holder_6 = Record({
  $id: Now.ID['enhanced_policy_holder_3006'],
  table: 'x_hete_clv_maximiz_policy_holders',
  data: {
    customer_id: 'CUST-2024-3006',
    first_name: 'David',
    last_name: 'Rodriguez',
    name: 'David Rodriguez',
    email: 'david.rodriguez@realestate.invest',
    phone: '+15553006',
    age: 41,
    credit_score: 592,
    churn_risk: 88,
    risk: 'high',
    tier: 'bronze',
    lifetime_value: 12800,
    clv: 3200,
    renewal_date: '2025-02-10',
    engagement_score: 25,
    tenure_years: 4,
    preferred_channel: 'Phone',
    app_sessions_30_days: 2,
    website_visits_30_days: 1,
    quote_views: 22,
    clv_score: 2.1,
    credit_utilization_percent: 89,
    number_of_open_accounts: 1,
    number_of_closed_accounts: 6,
    delinquency_12m: 5,
    credit_inquiries_last_6m: 12,
    bankruptcies_flag: true,
    abandoned_journeys: 18,
    avg_session_time_min: 1,
    risk_flags: 'Real Estate Investment, High Risk, Recent Bankruptcy',
    missing_coverage: 'All Essential Coverages'
  }
});

export const enhanced_policy_holder_7 = Record({
  $id: Now.ID['enhanced_policy_holder_3007'],
  table: 'x_hete_clv_maximiz_policy_holders',
  data: {
    customer_id: 'CUST-2024-3007',
    first_name: 'Lisa',
    last_name: 'Thompson',
    name: 'Lisa Thompson',
    email: 'lisa.thompson@nurse.health',
    phone: '+15553007',
    age: 43,
    credit_score: 756,
    churn_risk: 18,
    risk: 'low',
    tier: 'gold',
    lifetime_value: 42000,
    clv: 11500,
    renewal_date: '2025-05-12',
    engagement_score: 81,
    tenure_years: 9,
    preferred_channel: 'Mobile App',
    app_sessions_30_days: 22,
    website_visits_30_days: 14,
    quote_views: 3,
    clv_score: 7.5,
    credit_utilization_percent: 19,
    number_of_open_accounts: 5,
    number_of_closed_accounts: 2,
    delinquency_12m: 0,
    credit_inquiries_last_6m: 1,
    bankruptcies_flag: false,
    abandoned_journeys: 1,
    avg_session_time_min: 9,
    risk_flags: 'Healthcare Worker, Stable Income, Low Risk',
    missing_coverage: 'Professional Liability Enhancement'
  }
});

export const enhanced_policy_holder_8 = Record({
  $id: Now.ID['enhanced_policy_holder_3008'],
  table: 'x_hete_clv_maximiz_policy_holders',
  data: {
    customer_id: 'CUST-2024-3008',
    first_name: 'James',
    last_name: 'Anderson',
    name: 'James Anderson',
    email: 'james.anderson@transport.logistics',
    phone: '+15553008',
    age: 55,
    credit_score: 643,
    churn_risk: 65,
    risk: 'high',
    tier: 'silver',
    lifetime_value: 28000,
    clv: 7200,
    renewal_date: '2025-03-08',
    engagement_score: 45,
    tenure_years: 11,
    preferred_channel: 'Phone',
    app_sessions_30_days: 8,
    website_visits_30_days: 4,
    quote_views: 12,
    clv_score: 4.8,
    credit_utilization_percent: 68,
    number_of_open_accounts: 3,
    number_of_closed_accounts: 3,
    delinquency_12m: 2,
    credit_inquiries_last_6m: 5,
    bankruptcies_flag: false,
    abandoned_journeys: 9,
    avg_session_time_min: 3,
    risk_flags: 'Transportation Industry, Economic Dependency',
    missing_coverage: 'Commercial Vehicle Enhancement'
  }
});

export const enhanced_policy_holder_9 = Record({
  $id: Now.ID['enhanced_policy_holder_3009'],
  table: 'x_hete_clv_maximiz_policy_holders',
  data: {
    customer_id: 'CUST-2024-3009',
    first_name: 'Maria',
    last_name: 'Garcia',
    name: 'Maria Garcia',
    email: 'maria.garcia@legal.law',
    phone: '+15553009',
    age: 39,
    credit_score: 785,
    churn_risk: 12,
    risk: 'low',
    tier: 'platinum',
    lifetime_value: 78000,
    clv: 22000,
    renewal_date: '2025-04-05',
    engagement_score: 89,
    tenure_years: 8,
    preferred_channel: 'Email',
    app_sessions_30_days: 25,
    website_visits_30_days: 18,
    quote_views: 2,
    clv_score: 8.7,
    credit_utilization_percent: 15,
    number_of_open_accounts: 7,
    number_of_closed_accounts: 1,
    delinquency_12m: 0,
    credit_inquiries_last_6m: 0,
    bankruptcies_flag: false,
    abandoned_journeys: 0,
    avg_session_time_min: 11,
    risk_flags: 'Legal Professional, High Income, Low Risk',
    missing_coverage: 'Cyber Liability for Law Practice'
  }
});

export const enhanced_policy_holder_10 = Record({
  $id: Now.ID['enhanced_policy_holder_3010'],
  table: 'x_hete_clv_maximiz_policy_holders',
  data: {
    customer_id: 'CUST-2024-3010',
    first_name: 'Christopher',
    last_name: 'Wilson',
    name: 'Christopher Wilson',
    email: 'christopher.wilson@freelance.creative',
    phone: '+15553010',
    age: 31,
    credit_score: 658,
    churn_risk: 55,
    risk: 'medium',
    tier: 'bronze',
    lifetime_value: 22000,
    clv: 5800,
    renewal_date: '2025-07-20',
    engagement_score: 52,
    tenure_years: 2,
    preferred_channel: 'Mobile App',
    app_sessions_30_days: 35,
    website_visits_30_days: 28,
    quote_views: 18,
    clv_score: 4.9,
    credit_utilization_percent: 62,
    number_of_open_accounts: 2,
    number_of_closed_accounts: 2,
    delinquency_12m: 1,
    credit_inquiries_last_6m: 4,
    bankruptcies_flag: false,
    abandoned_journeys: 8,
    avg_session_time_min: 3,
    risk_flags: 'Freelancer, Irregular Income, Young Professional',
    missing_coverage: 'Professional Indemnity, Health Insurance'
  }
});